services:
  database:
    image: postgres
    container_name: td-customer-db
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
      - ./.docker/postgresql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=tdCustomer
      - POSTGRES_PASSWORD=tdCustomer
      - POSTGRES_USER=tdCustomer

  backend:
    build: ./td-customers-api
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=database
    depends_on:
      - database

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - backend
