services:
  database:
    image: postgres:15
    container_name: td-customer-db
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=tdCustomer
      - POSTGRES_PASSWORD=tdCustomer
      - POSTGRES_USER=tdCustomer
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  postgres_data:
